inferno-framework/inferno-reference-server

README.md, upload.rb
Fixes upload and adds example bearer token to README for new token format.
=> Token fixes

README.md, src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java, src/main/webapp/WEB-INF/templates/app-launch.html, src/main/webapp/WEB-INF/templates/authorization.html, src/main/webapp/WEB-INF/web.xml
Updated app-launch url to be reference-server/app-launch, so it would not be on base of the server. This is required for site overlay, as multiple apps will be deployed on the same server
Please test with site overlay and standalone
For site overlay testing, to upload the sample data correctly please update 
FHIR_SERVER = 'http://localhost:8080/r4'
to
FHIR_SERVER = 'http://localhost/r4'
=> Update app launch url

README.md, src/main/java/org/mitre/fhir/authorization/ServerConformanceWithAuthorizationProvider.java, src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
Fixes the List profile in the CapabilityStatement
Before:
http://hl7.org/fhir/StructureDefinition/ListResource
After:
http://hl7.org/fhir/StructureDefinition/List
=> FI-695 Fix List Profile

src/main/java/org/mitre/fhir/authorization/FakeOauth2AuthorizationInterceptorAdaptor.java, src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
if you don't specify any resource, the fhir reference server will still allow it through
=> allow service calls with no resource

src/main/java/org/mitre/fhir/authorization/AuthorizationViewController.java, src/main/java/org/mitre/fhir/authorization/ServerConformanceWithAuthorizationProvider.java, src/main/webapp/WEB-INF/templates/authorization.html, src/main/webapp/WEB-INF/templates/patient-picker.html, src/main/webapp/js/authorize.js, src/main/webapp/js/patient-picker.js, src/test/java/org/mitre/fhir/wellknown/TestWellKnownEndpoint.java
now after the user selects a patient, it takes them to a page where they can select which of the scopes they would like to approve
note the ui is pretty simple, so if anyone thinks we should update it to make it loop better let me know!
=> added ability to choose which scopes you approve the user

README.md, src/main/java/org/mitre/fhir/authorization/token/TokenController.java, src/main/java/org/mitre/fhir/authorization/token/TokenManager.java, src/test/java/org/mitre/fhir/authorization/token/TestTokenManager.java
fixed bug where tokens weren't being revoked, updated readme to have token revoke
=> revoke token fixes

README.md
Update the readme to reflect the correct token revocation endpoint.
=> Update Token Revocation Endpoint in README

README.md
Updated the README to specify the requirement to run the reference server with java 11 if running it manually
=> updated readme to specify java version

src/main/java/org/mitre/fhir/authorization/AuthorizationController.java, src/main/java/org/mitre/fhir/authorization/FakeOauth2AuthorizationInterceptorAdaptor.java, src/main/java/org/mitre/fhir/authorization/ServerConformanceWithAuthorizationProvider.java, src/main/java/org/mitre/fhir/wellknown/WellKnownAuthorizationEndpointController.java, src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
Added Service element
Added token revocation to capability and well known to remove other warning
See test SPA-OSD-04 in Inferno Program
=> Added Service to Capability statement to fix warning

README.md, docker-compose.yml, pom.xml, src/main/java/org/mitre/fhir/authorization/FakeOauth2AuthorizationInterceptorAdaptor.java, src/main/java/org/mitre/fhir/authorization/token/TokenManager.java, src/test/java/org/mitre/fhir/authorization/TestAuthorization.java, src/test/java/org/mitre/fhir/authorization/token/TestTokenManager.java
Redoing `added checking for skip token auth environment var` pr https://github.com/inferno-community/inferno-reference-server/pull/23 to handle rebase problems, should be working now
=> Fi 1036 rebase

src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java, src/test/java/org/mitre/fhir/utils/TestFhirReferenceServerUtils.java
Removes the custom deployment support to avoid unecessary technical debt
=> undoing the custom deployment as it is no longer necessary

src/main/webapp/WEB-INF/templates/authorization.html, src/main/webapp/js/authorize.js
Make the checkboxes easier to select/deselect by allowing the user to click on their lables
=> made checkbox labels selectable

src/main/java/org/mitre/fhir/authorization/ServerConformanceWithAuthorizationProvider.java
Value was already hard coded into reference server, just needed to correct it to what seems like the correct value
https://www.hl7.org/fhir/capabilitystatement-definitions.html#CapabilityStatement.rest.security
https://www.hl7.org/fhir/valueset-restful-security-service.html
=> FI-1112 Fix CapabilityStatement validation errors

src/main/webapp/WEB-INF/templates/authorization.html, src/main/webapp/WEB-INF/templates/patient-picker.html
Updates the cache busting query strings.
None.
Updates the cache busting query strings.
Run standalone launch tests to make sure pages load and respond correctly.
=> Update cache busting querying string

pom.xml
- Add support for Bulk Data Group Export (#52)
- Add additional Group resource with id `1a` (#57)
- Updates cache busting query strings (#59)
=> Inferno Reference Server v1.1.0

pom.xml
* Populate `sub` claim on OpenID tokens.
=> Inferno Reference Server v1.1.1

src/main/webapp/WEB-INF/templates/landing.html, src/main/webapp/WEB-INF/templates/tmpl-banner.html
* Change copy/content from ticket
* Whitespace changes
None.  Just copy / content changes.
None except markup.
Boot app and look at HTML / CSS.  I was unable to do this because of a maven timeout.
=> Cleanup reference server landing page

src/main/java/org/mitre/fhir/authorization/AuthorizationController.java, src/main/java/org/mitre/fhir/bulk/AuthorizationBulkDataExportProvider.java
This branch updates the bulk data implementation to support SMART v2 scopes and export the additional resources needed by US Core 5.
=> FI-1833: Bulk Data Fixes

Dockerfile, src/main/resources/capability-statement-template.json
Add ServiceRequest and RelatedPerson to CapabilityStatement.
=> FI-1900: Update CapabilityStatement for US Core 5

docker-compose.yml, us-core-resources/d831ec91-c7a3-4a61-9312-7ff0c4a32134.json, us-core-resources/e91975f5-9445-c11f-cabf-c3c6dae161f2.json
Add us-core-sex extension to Patient resource for US Core v6.1.0
=> Add patient us-core-sex extension

pom.xml
=> Release 2.1.0

pom.xml
Bumping the version to 2.2.0 for release
=> Release 2.2.0

pom.xml
Bumping the version to 2.2.1 for release
=> Release 2.2.1

resources/uscore_bundle_patient_85.json
This PR fixes JIRA FI-2682
Add four QuestionnaireResponse resources to Patient 85
* Reload data to reference server.
* Run US Core Test Suite 6.0.1 QuestionnaireResponse test group. (This test group is not automatically running)
* Verify all tests are passed
=> FI-2682 Add QuestionnaireResponse resources to Patient 85

resources/uscore_bundle_patient_355.json, resources/uscore_bundle_patient_85.json
This PR fixed two JIRA ticket:
FI-2810: Incorrect display text
FI-2810: Add resources for Screening and Assessment guidance
Update Reference server
Run US Core v6.1.0 test suite
These test groups shall pass:
* 2.23 Observation Simple Tests
* 2.33 Observation Screening and Assessment Tests
* 2.49 Screening and Assessment Guidance  (need latest US Core Test Suite)
=> FI-2810 Fix disply text for Observation. Add resources for Screening and Assessment

resources/dtr_bundle_patient_pat015.json
Add bundle to support DTR test kit Respiratory Assist Device questionnaire workflow. This includes all the resources necessary for a DTR SMART App to pre-populate the questionnaire.
=> FI-2808: DTR Bundle

resources/pdex_bundle_patient_999.json, resources/pdex_proxy_group_patient_999.json, src/main/resources/hapi.properties
Adds patient data for PDex testing
=> FI - 2513 PDex data

pom.xml
Bumping the version number for release 3.1.0
=> Release 3.1.0

.github/workflows/docker.yml
Build docker images on any PR or push to main.
Adds CI workflow.
See `.github/workflows/docker.yml`.
Examine the Github Actions for this PR.
=> Enable docker build workflow

resources/uscore_bundle_patient_85.json
This PR fixes
* Replace Patient's ethnicity code from ASKU to 2186-5
* Replace Procedure's x-ray display from "Plain chest X-ray (procedure)" to "Plain X-ray of chest (procedure)"
Run US Core v3.1.1 test suite, Patient validation shall pass
Run US Core v6.1.0 test suite, Procedure validation shall pass
=> Fix patient's ethnicity and Procedure's code for x-ray

src/main/java/org/mitre/fhir/wellknown/WellKnownAuthorizationEndpointController.java
Adds the `scopes_supported` field to the well-known smart-configuration endpoint, per:
https://hl7.org/fhir/us/core/STU7/scopes.html#additional-us-core-requirements
The smart-configuration endpoint now contains a `scopes_supported` field with the set of scopes the server supports. This includes "launch/patient", "openid", "fhirUser", "offline_access", and the set of all SMART 2.x resource-level scopes and granular scopes expected per US Core 7. **Note** this does not currently include any wildcard scopes or SMART v1 style scope. These would be easy to add, but the field is not required to be exhaustive so I've left them out. Happy to add them if people prefer.
The list is generated programmatically in the WellKnownAuthorizationEndpointController -- all resource types are theoretically …
=> FI-2868: Add scopes_supported to smart-configuration

pom.xml
Bumping the version number for release 3.2.0
=> Release 3.2.0

pom.xml
Bump version for release 3.2.1
=> Release 3.2.1

resources/carin_bundle_patient_888.json
Add Bundle to `resources` directory that includes examples of resources for each Carin for Blue Button profile with each MS element populated.
Ensure Bundle of Carin resources is valid and can be accessed on the Inferno Reference server
=> FI-3357: Add Carin For Blue Button Resources

resources/carin_bundle_patient_888.json
Additional CARIN resource bundle fixes/improvements including changing the Patient last name from `Example1` to `Smith`, changing the RelatedPerson last name from `Example1` to `Jones` and changing the Patient Unique Member Identifier system to `http://inferno.healthit.gov/reference-server/r4/uniquememberidentifier`.
=> FI-3357 Carin For Blue Button Resources Fix

pom.xml
Bump version for release 3.2.2
=>  Release 3.2.2

resources/pdex_bundle_patient_999.json
- Includes the updated PDex resources by @karlnaden, and merging this allows us to close #198
=> FI-3742 migrate changes

pom.xml
Bump version for release 4.0.0
=> Release 4.0.0
