inferno-framework/inferno-reference-server

- .dockerignore
Fix the Docker Hub builds by removing the leading slashes from folder unignore statements in `.dockerignore`.
See a successful build here: https://hub.docker.com/repository/registry-1.docker.io/infernocommunity/inferno-reference-server/builds/1a0d9c0d-b051-4490-ab6a-ddb61cba5251
> Fix docker hub builds

- src/main/webapp/js/authorize.js
Having a blank line in there was confusing, added placeholder text:
> Add Patient Name Absent message if no name in picker.

- README.md
- src/main/java/org/mitre/fhir/authorization/ServerConformanceWithAuthorizationProvider.java
- src/main/java/org/mitre/fhir/authorization/exception/InvalidClientIdException.java
- src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java
- src/main/webapp/WEB-INF/templates/app-launch.html
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/js/authorize.js
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorizationWithNoData.java
- src/test/java/org/mitre/fhir/authorization/TestFhirReferenceServerUtils.java
- src/test/java/org/mitre/fhir/authorization/TestWellKnownEndpoint.java
Changed the root url for the fhir reference server to <base>/reference-server , so now each servlet is under the url reference-server
> Make root url reference server

- src/main/java/org/mitre/fhir/authorization/ServerConformanceWithAuthorizationProvider.java
- src/main/webapp/WEB-INF/templates/authorization.html
- src/main/webapp/js/authorize.js
- src/main/webapp/js/patient-picker.js
- src/test/java/org/mitre/fhir/wellknown/TestWellKnownEndpoint.java
Updated support for checking the aud and launch params.
The reference server should now pass the SMART App Launch Error: Invalid AUD Parameter and SMART App Launch Error: Invalid Launch Parameter in the Other tests (see branch `negative-launch-tests`  in inferno-program)
Also updated authorization page to be authorization which will redirect to the patient picker if no patient_id in the url params
> Server now checks the aud and launch params on the authorization page

- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
- src/main/java/org/mitre/fhir/authorization/FakeOauth2AuthorizationInterceptorAdaptor.java
- src/main/java/org/mitre/fhir/authorization/token/Token.java
- src/main/java/org/mitre/fhir/authorization/token/TokenManager.java
- src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java
- src/main/java/org/mitre/fhir/utils/FhirUtils.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorizationWithNoData.java
- src/test/java/org/mitre/fhir/authorization/token/TestTokenManager.java
- src/test/java/org/mitre/fhir/utils/TestUtils.java
Removed the encoded scopes from the bearer token, and instead store that information on the server.  This means that someone with the token cannot change the scopes by understanding how the token is structured and the token is simpler in general.  Current this change is only for the bearer token, and not the code (which is not stored on the reference server at the moment, but will be updated in https://oncprojectracking.healthit.gov/support/browse/FI-939
> updated refresh token to contain scope instead of the token itself

- README.md
- docker-compose.yml
- pom.xml
- src/main/java/org/mitre/fhir/authorization/FakeOauth2AuthorizationInterceptorAdaptor.java
- src/main/java/org/mitre/fhir/authorization/token/Token.java
- src/main/java/org/mitre/fhir/authorization/token/TokenManager.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
- src/test/java/org/mitre/fhir/authorization/token/TestTokenManager.java
Removing the option to Skip Authentication and instead adding a env var to contain a custom bearer token.
To Test, set an env var CUSTOM_BEARER_TOKEN to value and try to enact a request with that bearer token.
> Fi 1093 change skip auth to specifiy token value

- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
- src/main/java/org/mitre/fhir/wellknown/WellKnownAuthorizationEndpointController.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
Added the subject identifier claim to the OpenID token. 
See content of **id_token_payload_json**
Simple addition of a subject string. 
Run core outside of docker with g10 enabled and see the output of test 1.3.01 to see the sub claim in the OpenID token payload.
> FI-1499 Sub Claim

- src/main/resources/capability-statement-template.json
Update the capability statement served up at the `/metadata` endpoint to meet US Core v4.0.0
Modified capability statement at `/metadata` endpoint.
Add the `"instantiates"` element and value
Run the server locally, hit `/metadata` using Postman. Visually confirm change.
> FI-1710: Update Metadata

- src/main/java/org/mitre/fhir/authorization/AuthorizationViewController.java
During the EHR Launch in G10, request for authorization is made using a POST requests. This adds support for handling POST authorization request. 
Directs properly-formed POST authorization requests to the scopes view.
Added a POST Mapping to the authorization endpoint. The mapping uses the request URL and parameters in the body of the request to construct an alternative request url that redirects to the GET Mapping. Flow then continues as it does for typical GET authorization requests.
Run the reference server locally and use it as the FHIR endpoint when running the g10 suite locally (I recommend using the command G10_VALIDATOR_URL=http://localhost:4545 INFERNO_HOST=http://localhost:4567 ASYNC_JOBS=false bundle exec puma to avoid docker/localhost quirks). Run the EHR launch group in …
> FI-1729: Post Authorization

- src/main/java/org/mitre/fhir/wellknown/WellKnownAuthorizationEndpointController.java
Add `grant_types_supported` to `.well-known/smart-configuration`
`.well-known/smart-configuration` now contains new element
Hard-coded the grant types
Run the server locally and access the `/.well-known/smart-configuration` endpoint to visually confirm the `grant_types_supported` element. Then, run G10 test kit locally with Ruby, using the SMART STU2 selection, and point it towards your local server instance. Confirm test **1.2.02** passes.
> FI-1766: Add fields to `.well-known/smart-configuration` and update capabilities field

- src/main/webapp/WEB-INF/templates/app-launch.html
- src/main/webapp/js/authorize.js
Removed the patient-picker page from the EHR Launch flow. 
Upon receiving an authorization request from within an EHR launch – as denoted by the url containing the `launch` parameter – the reference server prevents navigation to the patient-picker and allows for immediate scope granting. 
Altered the `authorization.js` file to check the url for the `launch` parameter and to append `patient_id=launch` to the url, if the launch parameter has an expected value. By adding a `patient_id` parameter, the patient-picker is circumvented.
Run the reference server locally and use it as the FHIR endpoint when running the g10 suite locally (I recommend using the command `G10_VALIDATOR_URL=http://localhost:4545 INFERNO_HOST=http://localhost:4567 ASYNC_JOBS=false bundle exec puma` to avoid …
> FI-1672: Remove patient-picker from EHR launch

- src/main/java/org/mitre/fhir/app/launch/AppLaunchController.java
- src/main/java/org/mitre/fhir/utils/FhirUtils.java
Any method in the `FhirUtils` class (such as `getAllEncounters`) that receives a Bundle and then extracts every resource in that Bundle into an array will issue follow-up `GET_PAGE` request(s), if the Bundle is big enough to need muliple pages. However, the Bearer Token was not being passed as part of those requests, causing them to be denied and the "Invalid Token" error to be thrown. This was actually not an error unique to `getAllEncounters`, but every `getAll` method in `FhirUtils`. However, it only arose while testing `getAllEncounters` because Encounters are the only resource whose quantity requires multiple pages in the returned Bundle.
No longer throws `Invalid Token` when calling `getAllEncounter`.
Add Bearer Token to subsequent `GET_PAGE` request when accessing pages in Bundle. …
> FI-1758: Address "Invalid Token" Error raised by getAllEncounters

- src/main/java/org/mitre/fhir/ReadOnlyInterceptor.java
- src/test/java/org/mitre/fhir/TestReadOnlyInterceptor.java
Allow GET_PAGE requests to be accepted when the server is in ReadOnly mode. 
GET_PAGE requests will not be blocked nor return a 'the server is currently read only' response/error, but will be accepted by the server.
Added the GET_PAGE request to the list of acceptable requests within the interceptor.
Do a search and attempt to read second page of results.
> FI-1759: Allow GET_PAGE requests in ReadOnly Interceptor

- src/main/resources/capability-statement-template.json
This branch updates the CapabilityStatement to remove warnings from the bulk data tests.
> FI-1671: Fix bulk data warnings

- src/main/java/org/mitre/fhir/app/launch/AppLaunchController.java
- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
- src/main/java/org/mitre/fhir/authorization/token/Token.java
- src/main/java/org/mitre/fhir/utils/FhirReferenceServerUtils.java
- src/main/java/org/mitre/fhir/utils/FhirUtils.java
- src/main/webapp/WEB-INF/templates/app-launch.html
- src/main/webapp/WEB-INF/templates/authorization.html
- src/main/webapp/WEB-INF/templates/patient-picker.html
- src/main/webapp/js/app-launch.js
- src/main/webapp/js/authorize.js
- src/main/webapp/js/patient-picker.js
- src/test/java/org/mitre/fhir/app/launch/TestAppLaunchController.java
- src/test/java/org/mitre/fhir/utils/TestFhirReferenceServerUtils.java
- src/test/java/org/mitre/fhir/utils/TestFhirUtils.java
Add support for selecting the encounter from which an EHR launch occurs, and then passing that encounter information throughout the authorization flow.
The Reference Server App Launch page now includes a dropdown containing the encounters associated with each stored patient. Both the selected patient and encounter are passed to app via the launch context parameter. 
The patient-picker is then ignored (will include changes from this [PR](https://github.com/inferno-framework/inferno-reference-server/pull/70)). The encounter selected is then added to the token (and the refresh token). In this example, the app launch occurred from within Encounter 301 of Patient 232.
- The Patient ID dropdown was hard-coded, but is now dynamic (as is encounter). These dropdowns take a half second to populate, …
> FI-1727: Encounter Context in EHR Launch

- us-core-r4-resources/d831ec91-c7a3-4a61-9312-7ff0c4a32134.json
- us-core-r4-resources/e91975f5-9445-c11f-cabf-c3c6dae161f2.json
This PR updates the two transaction Bundle JSON files to match the latest data update for US Core 5
This PR also fixes that two Observation resources for Patient/85 in US Core 4.0 were mistakenly added to the Provenance of Patient/355
> Update transaction files. 

- pom.xml
- src/main/webapp/WEB-INF/templates/landing.html
> FI-1771: Update landing page to mention new standards supported

- src/main/java/org/mitre/fhir/bulk/AuthorizationBulkDataExportProvider.java
- src/test/java/org/mitre/fhir/bulk/AuthorizationBulkDataExportProviderTest.java
This branch:
- Removes caching from bulk data, so all requests won't share the same id
- Makes the server return a 404 for status requests of cancelled jobs
To test:
- Run the g10 bulk data tests
- Get the status url and bearer token from the delete request
- Make a status request using that url and token in postman. You should get a 404
> FI-1740: Handle deleted bulk requests

- README.md
- docker-compose.yml
- src/main/java/org/mitre/fhir/MitreJpaServer.java
- src/test/java/org/mitre/fhir/TestReadOnlyInterceptor.java
- src/test/java/org/mitre/fhir/app/launch/TestAppLaunchController.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
- src/test/java/org/mitre/fhir/bulk/AuthorizationBulkDataExportProviderTest.java
- src/test/java/org/mitre/fhir/bulk/TestBulkInterceptor.java
- src/test/java/org/mitre/fhir/utils/TestFhirUtils.java
Server now defaults to read only mode if the `READ_ONLY` environment variable is not set.
> FI-1770: Default to read only

- us-core-resources/d831ec91-c7a3-4a61-9312-7ff0c4a32134.json
- us-core-resources/e91975f5-9445-c11f-cabf-c3c6dae161f2.json
This change updates codes where the display value doesn't match a preferred display value from the code system. All tests for US Core should now pass.
NOTE: this is based off the US Core 6.0.0 changes, since those are already in prod. Recommend merging that prior to this.
The set of modified resources as a transaction bundle with PUTs is here:
[fi-1988-update-codes.json.txt](https://github.com/inferno-framework/inferno-reference-server/files/11774751/fi-1988-update-codes.json.txt)
Clear out your previous instance (https://github.com/inferno-framework/inferno-reference-server#resetting-the-server) so the initdb.sql is loaded when you start it up again. 
Point the US Core Test Kit at your local instance.
All tests should pass except for TLS tests, here's a snippet of 6.0.0 but it should …
> FI-1988: Fix code displays

- .github/inferno/docker-compose.yml
Update to go along with moving inferno images off of the onchealthit org.
> FI-1962: Update inferno docker image org

- .github/dependabot.yml
- .github/workflows/maven_ci.yml
This PR enables dependency management with dependabot:
1. The `dependabot.yml` file tells dependabot this is a maven-based repo and it should be able to handle simple version bumps. 
References:  
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates  
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems  
2. The new CI workflow step will enable security warnings on the security tab.   Also note the CI was pointing to branch name `master` not `main` so I updated that. All of the current workflows will need that updated but I fear a lot might not work so I'm going to save the other ones for …
> FI-2154 Enable dependabot for dependency management

- src/main/java/org/mitre/fhir/bulk/AuthorizationBulkDataExportProvider.java
This branch adds new US Core 6 resources to the bulk data export.
If you run the g10 bulk data tests on qa with US Core 6, three tests will skip because the resources aren't exported. To see the fix:
- Run the g10 tests locally
- `docker compose build`
- `docker compose up`
- In the g10 tests, select US Core 6. Use the preset, but make the host `http://localhost:8080` when you run the bulk data tests.
- You should see the that the resources are included in the export and the tests pass.
> FI-2203: Add US Core 6 resources to bulk export

- docker-compose.yml
- us-core-resources/d831ec91-c7a3-4a61-9312-7ff0c4a32134.json
- us-core-resources/e91975f5-9445-c11f-cabf-c3c6dae161f2.json
Added elements to resources in the server to account for new mandatory/must support elements introduced in US Core 7.  Changes made to both initdb and the transaction jsons.
Added two of each of the new Observation profiles introduced in US Core 7
`sex-for-clinical-use` has been removed from Patient 355
Rebuild the server and run the following tests from US Core 7 test kit.  All tests should pass:
- 16.07 All must support elements are provided in the MedicationDispense resources returned
- 18.09 All must support elements are provided in the Observation resources returned
- 36.08 Observation resources returned during previous tests conform to the US Core Average Blood Pressure Profile
- 46.11 All must support elements are provided in the ServiceRequest resources returned
- 47.05 All must …
> FI-23XX Update for US Core 7

- LICENSE
- NOTICE.md
- README.md
**Difference from other Data Rights PRs**: Added the Apache 2.0 license file, since it wasn't a part of the repository
Add data rights legend to the repository and remove copyright from README since it is no longer necessary.
> FI-2395: Data rights legend

- src/main/java/org/mitre/fhir/MitreServerConfig.java
- src/main/resources/capability-statement-template.json
The patient-export operation was listed under the Practitioner resource rather than the Patient resource in the capability statement, and the patient-export operation was not enabled on the server due to a specific setting, `IndexMissingFields` being disabled. This PR moves the patient-export operation to the correct resource in the Capability Statement (Patient), and it enables the IndexMissingFields setting so that the patient-export operation is enabled as well.
Bulk patient-export operation moved under Patient resource in capability statement, and patient-export operation is enabled on the server. 
Removed patient-export operation from Practitioner resource and moved under Patient resource in the Capability statement. set IndexMissingFields to enable to enable patient-export …
> FI-2366: Patient Export Operation Fix

- pom.xml
- src/test/java/org/mitre/fhir/utils/HapiFhirH2Dialect.java
- src/test/resources/hapi.properties
Replace the Derby DB which was only used for the unit test suite with [H2](https://www.h2database.com/) to address dependabot critical alerts. I would have preferred to just bump the Derby version but apparently the version with a fix either requires java 21 or a manual build of the dependency. 
This requires a custom "hibernate dialect" for H2 which is present in HAPI 5.7.9+ but we're still on 5.5, so I copied that class over.
Also bumps the logback version and jetty version at the same time to address other dependabot alerts.
None
See above
This change should have no visible impact. Note that the unit tests will fail if run on java 17+ - only java 11 seems to work at the moment. (also true on main)
> Dependabot updates + replace Derby database with H2

- resources/uscore_bundle_patient_85.json
Added `Location.identifier` and `Location.type` elements in support of US Core 7.0.0 MS requirements. This "PCP87052" Location appears to be the only one that the US Core 7 test actually finds so the fields were only added here.
Make sure to clear out the DB prior to running the reference server so the resources are reloaded, or alternatively set the `FORCE_LOAD_RESOURCES` env var to true.
> You can delete the server's data by stopping the containers with `docker-compose down` and then running `docker volume rm inferno-reference-server_fhir-pgdata` to remove the existing volume.
> FI-2492: Add Location.identifier and Location.type MS elements

- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
- src/main/java/org/mitre/fhir/authorization/exception/InvalidClientIdException.java
- src/main/java/org/mitre/fhir/authorization/exception/InvalidClientSecretException.java
- src/main/java/org/mitre/fhir/authorization/exception/OAuth2Exception.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorizationWithNoData.java
This PR changes the output format of errors raised on the `/authorization` endpoint to be JSON per the OAuth spec. https://datatracker.ietf.org/doc/html/rfc6749#section-5.2
Previously these were rendered by the default spring error page, which meant they were HTML. (If the request came in with an `Accept: application/json` header it would return some JSON, but still not the expected format, and I don't think the spec requires that header)
There should be no changes in terms of pass/fail -- all requests that would previously succeed should still succeed with the exact same response, all requests that would previously return an error should still return an error, with the same http status and general string description of what went wrong. The main change is that errors will now always be of …
> FI-2605: SMART error responses should be json

- src/main/java/org/mitre/fhir/landing/LandingViewController.java
- src/main/webapp/WEB-INF/templates/landing.html
Adds the confidential asymmetric client ID and key info to the landing page
Added 2 new items to the landing page template. I noticed a couple of the other items in the list had what look like copy&paste dup IDs so I cleaned those up as well.
Landing page is at `http://localhost:8080/reference-server/`
> FI-2635: add asymmetric auth client info to landing page

- resources/uscore_bundle_patient_85.json
This is a quick fix for an issue for loading QuestionnaireRepopnse resources into the HAPI server 7.0.1. Server rejects QuestionnireReponse resources with primitve extensions.
This PR replaces two `_questionnaire` primitive extensions  with regular `questionnaire` element.
> remove prmitive extension from QuestionnaireResponse resources

- src/main/java/org/mitre/fhir/InfernoReferenceServerWebConfig.java
Fixes the landing page at /reference-server/ by restoring the previous trailing slash behavior.
Behavior should match previous behavior prior to the HAPI 7 upgrade in 3.0.0 -- URLs with or without a trailing slash should be handled the same.
Changed the `UseTrailingSlashMatch` setting to true to match what the default what prior to Spring 6.
Note: this setting is deprecated, but in the interest of a smaller change this is the easiest way to ensure things work how they used to. The alternative is to update all mappings to include both paths: with and without trailing slash. And I wasn't clear from the spec whether things like `./well-known/smart-configuration` should explicitly allow a trailing slash.
The main URL in question is http://localhost:8080/reference-server vs …
> FI-2735: Restore previous url matching behavior - fixes landing page

- src/main/java/org/mitre/fhir/MitreServerConfig.java
We saw some issues in QA yesterday where two users received the same bulk export job ID and stomped on each other, and separately it seemed like jobs were being deleted unexpectedly. The root of all this is a config setting that allows bulk export job re-use when the parameters are identical. 
Previously when two bulk export requests would come in with identical params, the system might re-use the first job ID to respond to the second. Now each request will be an independent job. From an individual perspective there should be no visible impact, however this may have a performance impact if a lot of users try to export data simultaneously.
Set the param to false.
From the command line, you can run `curl -D - -H 'Prefer: respond-async' -H 'Authorization: Bearer SAMPLE_TOKEN' …
> Disable Bulk Export Job Reuse

- resources/uscore_bundle_patient_85.json
Original issue from: https://oncprojectracking.healthit.gov/support/browse/FI-2809
Observation/6e828cbf-5651-4cf4-b410-258e02965ea4
Observation/22d4f19b-6add-44a4-ae68-1c38d5d9f7f0
have wrong codes for US Core 7
Change these Observation.code from
"code": {
"coding": [
{
"system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-category",
"code": "treatment-intervention-preference",
"display": "Treatment Intervention Preference"
}
],
"text": "Treatment Intervention Preference"
},
to
"code": {
"coding": [
{
"system": "http://loinc.org",
"code": "75773-2",
"display": "Goals, preferences, and priorities for medical treatment"
}
],
"text": "Goals, preferences, and priorities for medical treatment"
},
Regenerate the database by 
`docker-compose build`
`docker-compose up`
Try the request below: …
> Fix US Core 7 Observation for treatment intervention preference

- resources/uscore_bundle_patient_355.json
- resources/uscore_bundle_patient_85.json
Fix reference server to be conforming to US Core 7 and HTI-1 
FI-2960: Add new sdoh category
FI-2876: PractitionerRole.endpoint MS element is missing
FI-2811: Add SmokingStatus Observation.valueQuantity
FI-2807: Fix MedicationRequest's medication_adherence extension
FI-2812: Populate MustSupport Location elements
Run US Core 7 test, all tests shall pass except:
* Observation Pregnancy validation test due to tx.fhir.org validation issue
* Simple Observation validation test due to tx.fhir.org validation issue
* Optional QuestionnaireResponse test due to missing data
> Reference server data update for US Core 7 and HTI-1

- resources/uscore_bundle_patient_85.json
This PR updates server data for two US Core updates:
1) Add extension to Patient.gender to test FI-3058
~2) Change one Smoking Status' Observation.effectiveDateTime to Observation.effectivePeriod to test FI-3060~
> FI-3080 Update Inferno Reference Server to latest US Core tickets

- resources/uscore_bundle_patient_85.json
Added SNOMED version `http://snomed.info/sct/731000124108` to the Observation resource.
US Core v5.0.1 passes Observation Social Hx test group, and both US Core v6.1.0, v7.0.0 pass Observation Pregnancy Intent test group.
See diff. 
1. Checkout this branch.
2. Reset and run reference server:
```
docker compose down
docker volume rm inferno-reference-server_fhir-pgdata
docker compose build
docker compose up
```
3. Run US Core v5.0.1, v6.1.0, v7.0.0 with input patient ids 85,355
> Fix Observation Social History/Pregnancy Intent code

- src/main/java/org/mitre/fhir/MitreJpaServer.java
- src/main/java/org/mitre/fhir/MitreServerConfig.java
- src/main/java/org/mitre/fhir/PathBasedCorsInterceptor.java
- src/main/java/org/mitre/fhir/app/launch/AppLaunchController.java
- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
- src/main/java/org/mitre/fhir/authorization/token/TokenController.java
- src/main/java/org/mitre/fhir/wellknown/WellKnownAuthorizationEndpointController.java
Enables CORS on the reference server per SMART 2.2: https://hl7.org/fhir/smart-app-launch/STU2.2/app-launch.html#considerations-for-cross-origin-resource-sharing-cors-support
> Servers that support purely browser-based apps SHALL enable [Cross-Origin Resource Sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) as follows:
> * For requests from any origin, CORS configuration permits access to the public discovery endpoints (.well-known/smart-configuration and metadata)
> * For requests from a client’s registered origin(s), CORS configuration permits access to the token endpoint and to FHIR REST API endpoints
In this case, we don't really want to implement a full client registration process, so we interpret the current Origin field as a client's "registered origin".
CORS …
> FI-3258: Add CORS support per SMART 2.2

- src/main/webapp/WEB-INF/templates/landing.html
Inferno Test Kit Authoring tutorial moved to /inferno-framework. Update link on the reference serve landing page.
Link should point to https://github.com/inferno-framework/tutorial-test-kit/wiki
> FI-3368 Update link to inferno test kit tutorial

- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
- src/test/java/org/mitre/fhir/authorization/TestAuthorization.java
- src/test/java/org/mitre/fhir/utils/TestUtils.java
The reference server has 3 conceptual clients - public, confidential asymmetric, and confidential symmetric. Previously the only authentication performed was checking the client secret if the ID provided was the confidential symmetric id, but it was possible to use the public or confidential asymmetric clients with any client secret, or the confidential asymmetric client without a client assertion. This PR enforces the appropriate auth mechanism for each client.  
This issue was identified on g10, which originally wasn't sending the token request correctly. The corresponding fix there was https://github.com/onc-healthit/onc-certification-g10-test-kit/pull/549 which was included in v6.0.1 (or in other words, the last version without the fix is v6.0.0) 
Clients can only authenticate with …
> FI-3044: Enforce the appropriate auth mechanism for each client

- pom.xml
Bumps HAPI to v7.6.0, just released a few days ago. Also bumps a couple other dependencies to their most recent versions. This should address most, hopefully all, of the high-priority dependabot alerts. Unfortunately that only updates when there's a push to main, so there may be a second PR after this to address further alerts.
Nothing should be new or different.
The items in dependencyManagement are changed as follows:
- commons-compress, spring-web, parsson: removed because the nested dependency is now up to date
- spring-boot: left as-is because the dependency is still out of date
- protobuf-java: added to address a dependabot alert because the dependency is still out of date
Dependencies list from a "pure" build (with all dependencyManagement removed): …
> FI-3191: Bump HAPI to v7.6.0

- resources/dtr_bundle_patient_pat015.json
This PR changes the Task resource in the `dtr_bundle_patient_pat015.json` file from a CDex Task to a PAS Task. This is to reflect changes to the DTR Light EHR Test suite in the davinci-dtr-test-kit based on this PR comment: https://github.com/inferno-framework/davinci-dtr-test-kit/pull/35#discussion_r1868310626.
- Task is now conformant to the [PAS Task](http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-task) profile rather than the [CDex Task Profile](http://hl7.org/fhir/us/davinci-cdex/StructureDefinition/cdex-task-attachment-request).
- Example PAS Task from the [PAS IG](http://hl7.org/fhir/us/davinci-pas/STU2/Task-AdditionalInformationTaskExample.html) instead of CDex Task.
- Run this branch locally and run [this …
> Change Task from CDex conformant to PAS

- README.md
Just two light additions to the README to point to the docker image, since the docker hub org name doesn't match the github org name and there's no other reference to the published image.
> Add reference to docker image name

- .github/workflows/maven_ci.yml
According to [this error](https://github.com/inferno-framework/inferno-reference-server/actions/runs/13635434189/job/38112910279?pr=201) the action cache@v2 is now depreciated
> Update maven_ci.yml to use actions/cache@v4

- pom.xml
Bumps a few direct and nested dependencies to address dependabot security alerts. Because of how these are defined in the pom, dependabot cannot create these PRs itself.
Run g10 or any other test kit against this and make sure nothing broke
> Bump dependencies [dependabot]

- resources/carin_2_1_SearchParameter-explanationofbenefit-insurer.json
Adds the ExplanationOfBenefit:insurer SearchParameter from the Carin4BB IG. Note this comes from the latest (STU 2.1) version of the IG but functionally it's the same as the earlier versions.
Enables searches using the `insurer` parameter on ExplanationOfBenefit resource - both as a direct parameter eg `/ExplanationOfBenefit?insurer=123` or as an include parameter eg `/ExplanationOfBenefit?_include=ExplanationOfBenefit:insurer`
Just added the search param file to resources so it's loaded at startup.
Reset the DB and run the server to load the new resources. Run the following sample requests:
```
GET {BASE_URL}/ExplanationOfBenefit?_include=ExplanationOfBenefit:insurer&patient=888
GET {BASE_URL}/ExplanationOfBenefit?insurer=c4bb-Organization
```
Running against the prod instance, these …
> FI-3405: Add EOB:insurer SearchParameter from Carin4BB

- resources/carin_proxy_group_patient_888.json
- resources/combo_proxy_group.json
- Add a group for the CARIN patient (888)
- Add a "combo" group containing patients from CARIN, PDex, and US Core
Additional groups to support targeting bulk exports via Group method for specific IG data
resources/carin_proxy_group_patient_888.json
resources/combo_proxy_group.json
> FI-3646: Add CARIN and combo Groups

- src/main/java/org/mitre/fhir/authorization/AuthorizationController.java
When running SMART test kit token introspection tests, the token introspection test fails because the response is missing the client_id field. This PR adds the `client_id` field to the internal Token model for tokens generated by backend services auth. The logic to report this field back out when set was already present, so no changes needed there. The `exp` field was also added, because that field is also required and missing but the error was obscured by the missing client_id. The logic to set exp was copied from elsewhere in the same file: https://github.com/inferno-framework/inferno-reference-server/blob/624dac3b239b4fc465f5b4f8825f3281a2469324/src/main/java/org/mitre/fhir/authorization/AuthorizationController.java#L468
On the SMART App Launch test kit, SMART v2.2:
1. Use the Inferno …
> FI-3996: Add client_id and exp to tokens generated for backend services
